export const HEADLINES = [
    "Transform Your Digital Presence",
    "Elevate Your Online Experience",
    "Next-Gen Web Solutions",
    "Innovative Digital Solutions",
    "Build the Future of the Web",
    "Unlock Your Digital Potential",
    "Seamless Web Experiences",
    "Cutting-Edge Technology at Your Fingertips",
    "Revolutionize Your Online Strategy",
    "Powerful Tools for Modern Developers",
    "Create, Deploy, and Scale with Ease",
    "Your Vision, Our Expertise",
    "Design Beyond Boundaries",
    "The Ultimate Web Development Toolkit",
    "Where Ideas Become Reality",
    "Empowering Your Digital Journey",
    "Smart Solutions for Smart Businesses",
    "Bridging the Gap Between Design and Functionality",
    "The Future of Web Development Starts Here",
    "Crafting Exceptional Digital Experiences"
  ];
  
  export const SUBHEADLINES = [
    "Create stunning websites that convert",
    "AI-powered web experiences",
    "Where creativity meets technology",
    "Redefining digital boundaries",
    "Tailored solutions for your business needs",
    "Fast, secure, and scalable web applications",
    "Designed for performance and user engagement",
    "Harness the power of modern web technologies",
    "From concept to deployment, we've got you covered",
    "Optimized for speed, accessibility, and SEO",
    "Turn your ideas into functional, beautiful websites",
    "Expertly crafted with attention to detail",
    "Innovative designs that stand out",
    "Built with the latest frameworks and tools",
    "User-centric designs that drive results",
    "Scalable solutions for growing businesses",
    "Seamless integration with your existing systems",
    "Responsive designs for every device",
    "Data-driven strategies for maximum impact",
    "Your success is our priority"
  ];